version: '3'
services:
  # basic
  basic:
    build: ./basic_all
    image: basic
    container_name: 'basic'
    hostname: basic
    networks:
      - basic
    ports:
      - "8888:80"
    volumes:
      - ./basic_all/src/basic/:/var/www/basic/
      - ./basic_all/src/basic/public/.htaccess:/etc/httpd/conf.d/.htaccess
      - ./basic_all/apache/basic.conf:/etc/httpd/conf.d/basic.conf
      - ./basic_all/php/php.ini:/etc/php.ini
      - ./basic_all/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    tty: true
    privileged: true
    command: /sbin/init
networks:
  basic:
