version: '2'
services:
  # jumphost
  jumphost:
    build: ./jumphost
    image: jumphost
    container_name: 'jumphost'
    ports:
      - "2201:22"
    networks:
      my_net:
        ipv4_address: 192.168.56.100
    hostname: jumphost
    tty: true
    privileged: true
    command: /sbin/init
  # web
  web:
    build: ./web
    image: web
    container_name: 'web'
    ports:
      - "2202:22"
      - "8880:80"
    networks:
      my_net:
        ipv4_address: 192.168.56.101
    hostname: web
    tty: true
    privileged: true
    command: /sbin/init
  # db
  db:
    build: ./db
    image: db
    container_name: 'db'
    ports:
      - "2203:22"
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      my_net:
        ipv4_address: 192.168.56.102
    hostname: db
    tty: true
    privileged: true
    command: /sbin/init
networks:
  my_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 192.168.56.0/24
        gateway: 192.168.56.1

