version: '2'
services:
  # web
  web:
    image: web                         # タグやimageIDの一部
    build:
      context: ./web                   # Dockerfileのあるディレクトリのパス
    container_name: web                # コンテナ名
    hostname: test-docker-web          # ホスト名
    ports:                             # ポート
     - 8080:80
    networks:
      my_net:
        ipv4_address: 192.168.56.100
    extra_hosts:
     - test-db:192.168.56.101
     - test-batch:192.168.56.102
    tty: true
    command: /usr/sbin/httpd -D FOREGROUND
  # db
  db:
    image: db                          # タグやimageIDの一部
    build:
      context: ./db                    # Dockerfileのあるディレクトリのパス
    container_name: db                 # コンテナ名
    hostname: test-docker-db           # ホスト名
    ports:                             # ポート
     - 3306:3306
    environment:                       # 環境変数
      MYSQL_ROOT_PASSWORD: password    # rootユーザーパスワード
    networks:
      my_net:
        ipv4_address: 192.168.56.101
    extra_hosts:
     - test-web:192.168.56.100
     - test-batch:192.168.56.102
  # batch
  batch:
    image: batch                       # タグやimageIDの一部
    build:
      context: ./batch                 # Dockerfileのあるディレクトリのパス
    container_name: batch              # コンテナ名
    hostname: test-docker-batch        # ホスト名
    networks:
      my_net:
        ipv4_address: 192.168.56.102
    extra_hosts:
     - test-web:192.168.56.100
     - test-db:192.168.56.101
    tty: true
    command: /usr/sbin/crond -n
networks:
  my_net:
    ipam:
      config:
      - subnet: 192.168.56.0/24
        gateway: 192.168.56.1

