version: '3'
services:
  # laravel
  laravel:
    build: ./laravel
    image: laravel
    container_name: 'laravel'
    hostname: laravel
    networks:
      - laravel
    ports:
      - "8888:80"
    volumes:
      - ./laravel/src/laravel_practice/:/var/www/html/laravel_practice/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    tty: true
    privileged: true
    command: /sbin/init
networks:
  laravel:
